#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os

# make sure that we are not in a git repo
exit_code = os.system("git status &>/dev/null")

if exit_code == 0:
    cwd = os.getcwd()
    print("you are sitting in %s which appears to be part of "
          "a git repository" % cwd)
    print("this command cannot be run in a git repository")
    print("please change your working directory before running this command")
    exit(1)

# retrieving package content
package_path = os.path.dirname(os.path.dirname(__file__))
template_path = os.path.join(package_path, "canai", "templates", "pred")
print(package_path)
print(template_path)

# TODO: create project folder

# TODO: copy template

# TODO: create git repo
